const countries = [
        { name: "السعودية", dialCode: "+966" },
        { name: "الإمارات", dialCode: "+971" },
        { name: "الكويت", dialCode: "+965" },
        { name: "مصر", dialCode: "+20" },
        { name: "الأردن", dialCode: "+962" },
        { name: "العراق", dialCode: "+964" },
        { name: "البحرين", dialCode: "+973" },
        { name: "عُمان", dialCode: "+968" },
        { name: "قطر", dialCode: "+974" },
        { name: "لبنان", dialCode: "+961" },
        { name: "سوريا", dialCode: "+963" },
        { name: "المغرب", dialCode: "+212" },
        { name: "الجزائر", dialCode: "+213" },
        { name: "تونس", dialCode: "+216" },
        { name: "ليبيا", dialCode: "+218" },
        { name: "اليمن", dialCode: "+967" },
        { name: "تركيا", dialCode: "+90" },
        { name: "إيران", dialCode: "+98" },
        { name: "الهند", dialCode: "+91" },
        { name: "باكستان", dialCode: "+92" },
        { name: "أفغانستان", dialCode: "+93" },
        { name: "الصين", dialCode: "+86" },
        { name: "اليابان", dialCode: "+81" },
        { name: "كوريا الجنوبية", dialCode: "+82" },
        { name: "الولايات المتحدة", dialCode: "+1" },
        { name: "كندا", dialCode: "+1" },
        { name: "المكسيك", dialCode: "+52" },
        { name: "البرازيل", dialCode: "+55" },
        { name: "الأرجنتين", dialCode: "+54" },
        { name: "فرنسا", dialCode: "+33" },
        { name: "ألمانيا", dialCode: "+49" },
        { name: "إيطاليا", dialCode: "+39" },
        { name: "إسبانيا", dialCode: "+34" },
        { name: "المملكة المتحدة", dialCode: "+44" },
        { name: "أستراليا", dialCode: "+61" },
        { name: "نيوزيلندا", dialCode: "+64" },
        { name: "جنوب أفريقيا", dialCode: "+27" },
        { name: "روسيا", dialCode: "+7" },
        { name: "أوكرانيا", dialCode: "+380" },
        { name: "السويد", dialCode: "+46" },
        { name: "النرويج", dialCode: "+47" },
        { name: "فنلندا", dialCode: "+358" },
        { name: "الدنمارك", dialCode: "+45" },
        { name: "سويسرا", dialCode: "+41" },
        { name: "النمسا", dialCode: "+43" },
        { name: "هولندا", dialCode: "+31" },
        { name: "بلجيكا", dialCode: "+32" },
        { name: "البرتغال", dialCode: "+351" },
        { name: "اليونان", dialCode: "+30" },
      ];
      
      export default countries;
      